name: CI
on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 24, 26 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}

      - name: Install core dependencies
        working-directory: core
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build core
        working-directory: core
        run: yarn build

      - name: Run core tests
        working-directory: core
        run: yarn test

  Documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install core dependencies
        working-directory: core
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build core
        working-directory: core
        run: yarn build

      - name: Install documentation dependencies
        working-directory: tsdoc
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build documentation
        working-directory: tsdoc
        run: yarn build

      - name: Run documentation tests
        working-directory: tsdoc
        run: yarn test

  Compiler-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 24, 26 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}

      - name: Install core dependencies
        working-directory: core
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build core
        working-directory: core
        run: yarn build

      - name: Install compiler test dependencies
        working-directory: compiler-tests
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Run compiler tests
        run: yarn all
        working-directory: compiler-tests