name: npm
on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          ref: ${{github.ref}}

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        working-directory: core
        run: yarn

      - name: Build
        working-directory: core
        run: yarn build

      - name: Test
        working-directory: core
        run: yarn test

      - name: Install compiler test dependencies
        working-directory: compiler-tests
        run: yarn

      - name: Run compiler tests
        working-directory: compiler-tests
        run: yarn all

      - name: Copy Readme
        working-directory: core
        run: cp ../README.md .

      - name: Publish
        working-directory: core
        run: npm publish