name: Sonar
on: push

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install c8
        run: yarn global add c8

      - name: Install dependencies
        working-directory: core
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build core
        working-directory: core
        run: yarn build

      - name: Get core code coverage
        working-directory: core
        run: c8 -r lcov yarn test -s

      - name: Install documentation dependencies
        working-directory: tsdoc
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build documentation
        working-directory: tsdoc
        run: yarn build

      - name: Get documentation code coverage
        working-directory: tsdoc
        run: c8 -r lcov yarn test -s

      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
